### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by royben** [amulware/awgraphics#12]
Are there any examples for using this library?

**Comment by amulware** [comment]
@royben 
There are no examples for the library specifically, but here are some resources that might help:

I got an article on my blog explaining the basics of using OpenTK for graphics here: http://genericgamedev.com/tutorials/opengl-in-csharp-an-object-oriented-introduction-to-opentk/

Otherwise, several of my other repos on GitHub use the library to varying degrees. Here are some of them:
https://github.com/amulware/genericgamedev-gpu-particles (uses basic vertex buffers, shaders, etc.)
https://github.com/amulware/genericgamedev-pixelation (similar, but more post-processing oriented)
https://github.com/amulware/syzygy (a multiplayer game prototype, uses basic 2d and font rendering)
https://github.com/amulware/ld33 (a singleplayer game prototype, uses both 2d and simple 3d rendering)
https://github.com/beardgame/td (the only thing I'm still working, and pretty much the only reason I work on this library every now and then right now - so far only 2d, sprites, fonts, but bound to use some more fancy stuff in the future, as my free time permits)

Unfortunately the only project using pretty much all parts of the library (a game called Roche Fusion) is closed source.

I hope this helps!
Feel free to let me know if you have any more specific questions.

**Comment by royben** [comment]
Thanks Paul, I will check those out.

**Comment by amulware** [comment]
@royben 
You can use [uniforms](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)) for those parameters, and then you don't have to recompile the shader. These can be changed for each draw call with [glUniform*](https://www.khronos.org/opengl/wiki/GLAPI/glUniform) functions (GL.Uniform* in OpenTK), and with [surface settings](https://github.com/amulware/awgraphics/tree/master/src/amulware.Graphics/Core/surfaces/settings) in my library.
